Feature/oc 184 implement new design profile page
OrdinaNederland/to-the-root-frontend pull request #11
Opened 2022-04-06 08:56 UTC by dennis-ordina

2022-04-06 13:59 UTC, DrKlonk requested changes
Over het algemeen netjes gewerkt en veel naar aparte componenten getrokken. Testen met een lege User brengt nog wel wat UX-punten aan het licht

2022-04-06 13:59 UTC, DrKlonk commented on components/global/PoweredByOrdina.vue
> +        src="~/assets/img/ordina_logo_with_slogan.png"
Ik had hier laatst een svg van gemaakt ergens in [deze](https://www.figma.com/file/o3CWD9TUjCK2BS084psrK1/AheadOfChange). Zou je er een svg van kunnen maken? Dat is veel mooier dan een png

2022-04-06 13:59 UTC, DrKlonk commented on pages/users/_username.vue
>  <template>
Als ik net een account heb gemaakt en naar mijn profiel ga, dan zie ik dit: 
![image](https://user-images.githubusercontent.com/6998380/161983888-4a1e3978-9381-48d3-84a3-32859dbd4d6b.png). Dit willen we wel anders denk ik.

- De rainbow als default profile image ben ik niet voor
Liever zoiets: 
![image](https://user-images.githubusercontent.com/6998380/161985151-dcf72ac3-3daa-4394-af2f-b50e8b7c76d0.png)

- Als name kan je de username pakken als de name niet is gevuld (zelfde voor de page title)
- Bij Get in touch wil je de iconen niet tonen als ze niet zijn gevuld
- De recent posts header wil je niet tonen als je geen posts hebt
- Je wil alvast wel kunnen zien wat je allemaal kan invullen op de settings. Bijvoorbeeld dat je ziet dat je tagline en bio nu leeg zijn, of een knop met "Update my profile" of iets dergelijks

2022-04-06 13:59 UTC, DrKlonk commented on pages/users/_username.vue
>  <template>
Ik mis ook de link naar de settings als ik op _mijn_ profiel ben

2022-04-06 13:59 UTC, DrKlonk commented on pages/users/_username.vue
>          store.getters['users/users'].find(
We willen in de backend checken op of de user zijn email wil verstoppen of niet, en zo ja, dan willen we die niet meesturen naar de frontend. Anders kan je m in je devtools alsnog gewoon zien

2022-04-06 13:59 UTC, DrKlonk commented on pages/users/_username.vue
> +        font-family: 'Poppins-SemiBold', sans-serif;
In design is deze ook Regular

2022-04-06 13:59 UTC, DrKlonk commented on pages/users/_username.vue
> +        background: linear-gradient(to top, $ordina-orange, $ordina-blue);
In design is deze omgekeerd

2022-04-06 13:59 UTC, DrKlonk commented on pages/users/_username.vue
> +          <RelatedPosts header="Recent Posts" :articles="sortedArticles" />
Ik mis de "More" balk uit het design met bijbehorende functionaliteit

2022-04-13 11:31 UTC, DrKlonk commented on pages/users/_username.vue
>          store.getters['users/users'].find(
Eerste comment is gefixt in https://github.com/OrdinaNederland/to-the-root-backend/pull/5/files

2022-04-15 08:13 UTC, dennis-ordina commented on components/global/PoweredByOrdina.vue
> +        src="~/assets/img/ordina_logo_with_slogan.png"
Wordt later gefixt

2022-04-15 10:20 UTC, dennis-ordina commented on pages/users/_username.vue
>  <template>
Dat je kan zien dat je bio enzo leeg zijn daar is niks voor ontworpen. Edit knop op je eigen profiel lijkt me voor nu voldoende. Een link naar mijn profiel (anders dan de edit knop) is in het design nergens te vinden, dus ik hou het bij een edit knop op je eigen profiel.

2022-04-15 11:02 UTC, dennis-ordina commented on pages/users/_username.vue
>          store.getters['users/users'].find(
> En de notificatiesettings hoeft iemand anders ook niet van mij te zien, die willen we afschermen

Daarvoor in de backend net zo'n PR maken als je voor het eerste comment hebt gedaan?

2022-04-15 11:04 UTC, dennis-ordina commented on pages/users/_username.vue
> +        background: linear-gradient(to top, $ordina-orange, $ordina-blue);
Klopt, maar dit is in het design inconsistent. Ben zo vrij geweest dit overal hetzelfde te laten.

2022-04-15 11:06 UTC, dennis-ordina commented on pages/users/_username.vue
> +        background: linear-gradient(to top, $ordina-orange, $ordina-blue);
Oh never mind Francisca heeft dit rechtgetrokken. Wel omgedraaid voor signup en login though, dus dat pas ik meteen wel aan.

2022-04-15 11:08 UTC, dennis-ordina commented on pages/users/_username.vue
> +          <RelatedPosts header="Recent Posts" :articles="sortedArticles" />
Klopt! Helemaal vergeten.

2022-04-15 11:09 UTC, dennis-ordina commented on pages/users/_username.vue
> +                      : require('~/assets/img/rainbow_ordina.png')
Dat ligt aan jou ;). Is lastig te zien met de dafault image.

2022-04-19 08:07 UTC, DrKlonk commented on pages/users/_username.vue
>  <template>
Bon. Dan pakken we dat later op

2022-04-19 08:08 UTC, DrKlonk commented on pages/users/_username.vue
>          store.getters['users/users'].find(
Yes, dus eigenlijk hoef je hier niks van te fixen

2022-04-19 08:08 UTC, DrKlonk commented on pages/users/_username.vue
> +        background: linear-gradient(to top, $ordina-orange, $ordina-blue);
Je weet nooit wat de designer ermee bedoelt hè ;)

2022-04-19 08:09 UTC, DrKlonk commented on pages/users/_username.vue
> +          <RelatedPosts header="Recent Posts" :articles="sortedArticles" />
Ik had verwacht dat ik dan meer posts zou zien van Barack, maar goed, er is geen functioneel ontwerp van, dus akkoord 👍

2022-04-19 08:16 UTC, DrKlonk approved these changes
Nice!

2022-04-19 08:16 UTC, DrKlonk commented on pages/users/_username.vue
> +      user.value.name ? user.value.name : user.value.username,
Mooie kans voor de [?? operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)

2022-04-19 08:16 UTC, DrKlonk commented on pages/users/_username.vue
> +      user.value.name ? user.value.name : user.value.username,
In combinatie met de optional chaining

2022-04-19 11:40 UTC, merged