Feature/oc 181 profile page setup
OrdinaNederland/to-the-root-frontend pull request #3
Opened 2022-03-30 13:29 UTC by DrKlonk

Creates a page for users/<username>
Remove the author page
Change the visuals and links on Article pages and CommentSection

No design is implemented yet, this is done in https://one-community.atlassian.net/browse/OC-184

2022-03-30 14:53 UTC, dennis-ordina commented
Er zit nog een build error in:

<img width="526" alt="Screenshot 2022-03-30 at 16 52 54" src="https://user-images.githubusercontent.com/92443937/160864443-b71fdd28-a4b3-4de3-b8fe-7b54cf9d65d7.png">

2022-03-31 07:45 UTC, dennis-ordina requested changes

2022-03-31 07:45 UTC, dennis-ordina commented on components/global/CommentItem.vue
> +      <NuxtLink class="comment__user-link" :to="`/users/${username}`">{{
Nice

2022-03-31 07:45 UTC, dennis-ordina commented on store/users.ts
> +    console.log('pushing', newUser)
Can you remove this?

2022-03-31 07:48 UTC, dennis-ordina commented
Can you change the seed-db script to reflect the new structure as well?

2022-03-31 13:21 UTC, dennis-ordina approved these changes

2022-03-31 13:21 UTC, dennis-ordina commented on components/global/CategoryCard.vue
> +<style lang="scss" scoped>
Hier ook weer double quotes xd weird

2022-03-31 14:28 UTC, DrKlonk commented on components/global/CategoryCard.vue
> +<style lang="scss" scoped>
Hier is t in de html, dus zoals verwacht

2022-03-31 14:28 UTC, merged