Feature/oc 177 update header signup and login
OrdinaNederland/to-the-root-frontend pull request #4
Opened 2022-03-31 08:42 UTC by dennis-ordina

2022-03-31 10:26 UTC, DrKlonk commented
Werkt nog niet lekker op mobiel als je wel ingelogd bent: 
![image](https://user-images.githubusercontent.com/6998380/161033084-c8f46a14-8c3e-45c7-b485-a709bfeea8a9.png)
Ik zou het tonen zoals je het hebt gedaan als je niet ingelogd bent. Dus dat je daar alleen PROFILE, SETTINGS en LOGOUT ziet onder een gradient border

2022-03-31 10:42 UTC, DrKlonk requested changes
Vooral mobiel werkt nog niet zo goed. En dat je een profile onder je profile hebt, dat laten we dan maar zo voor nu. Bovenaan de backlog na livegang

2022-03-31 10:42 UTC, DrKlonk commented on components/global/LoginBox.vue
> +      <div class="profile-dropdown">
Ik kan met mijn keyboard deze dropdown niet uitklappen

2022-03-31 10:42 UTC, DrKlonk commented on components/global/LoginBox.vue
> +    function profileHandler() {
Gebruiken we niet toch?

2022-03-31 10:42 UTC, DrKlonk commented on components/global/LoginBox.vue
> +          <NuxtLink to="/profile" class="profile-dropdown__link"
En deze naar `users/<username>`

2022-04-04 08:22 UTC, dennis-ordina commented on components/global/LoginBox.vue
> +      <div class="profile-dropdown">
Ticket voor aangemaakt. https://one-community.atlassian.net/browse/OC-190

2022-04-06 12:57 UTC, DrKlonk reviewed
Het is voor mij wel fijn als er bij zo een extra fix wel een comment staat wat er precies (extra) veranderd is. Dat is voor mij nu extra analyseren

2022-04-06 12:57 UTC, DrKlonk commented on components/global/LoginBox.vue
>        <div class="profile-dropdown">
![image](https://user-images.githubusercontent.com/6998380/161970850-4c3ff406-9004-495d-b4d8-18fc94286342.png)
Bij sommige screenwidths gaat het mis op padding aan de rechterkant. Ik mis wat ruimte en het pijltje valt weg

2022-04-06 12:57 UTC, DrKlonk commented on components/global/LoginBox.vue
>          <nav
Zou je het dezelfde padding en whitespace kunnen geven als het mobiele menu? Het voelt nu wat opgekropt. En het is dan consistenter

2022-04-06 12:57 UTC, DrKlonk commented on components/HeaderMenuLink.vue
> +  <div class="wrapper" tabindex="0">
Deze is niet nodig en zorgt voor een extra tab-moment per menu-item. De nuxt link is al tab-baar

2022-04-06 12:57 UTC, DrKlonk commented on components/HeaderMenuButton.vue
> +  <div class="wrapper" tabindex="0">
Deze is niet nodig en zorgt voor een extra tab-moment per menu-button. De button is al tab-baar

2022-04-06 12:57 UTC, DrKlonk commented on components/global/LoginBox.vue
> +    <!-- Logged in and on mobile -->
Kan weg, de v-if is duidelijk genoeg

2022-04-06 12:57 UTC, DrKlonk commented on components/global/LoginBox.vue
> +    const profileUrl = $auth.user ? `/users/${$auth.user.username}` : ''
Hier kan je de javascript optional chaining voor gebruiken, want er is altijd een user als de profile getoond moet worden met `to: /users/${$auth.user?.username}`

2022-04-19 07:54 UTC, DrKlonk approved these changes
Yes, veel beter zo! Het enige dat nog niet werkt is het met keyboard open klikken van de dropdown. En de title van de user page werkt niet. Maar daar kijken we (beide) later wel naar.

2022-04-19 12:13 UTC, merged